import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Hemu-UCDF and KEC Agritech",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",          // default favicon
    shortcut: "/favicon.ico",      // shortcut icon
    apple: "/apple-touch-icon.png" // optional for iOS
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
